# Database client for data visualization. Helpfull for manual testing.
version: '3.9'

services:

  adminer:
    container_name: repository-scraping-adminer
    hostname: adminer
    image: adminer:latest
    ports:
      - 8080:8080
    networks:
      - repository-scraper
    
networks:
  repository-scraper:
    name: repository-scraper
    external: true