# Databases' clients for data visualization simplifying manual testing
version: '3.9'

services:

  adminer:
    container_name: repository-scraping-adminer
    hostname: adminer
    image: adminer:latest
    ports:
      - 8080:8080
    networks:
      - repository-scraper
    depends_on:
      - database
  
  mongo-express:
    image: mongo-express:latest
    container_name: repository-scraping-mongo-express
    hostname: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_SERVER: mongo
    networks:
      - repository-scraper
    depends_on:
      - mongo