version: "3.9"

services:

  redis:
    container_name: repository-scraping-redis
    hostname: redis
    image: redis:7.0.11-alpine
    networks:
      - repository-scraper
    volumes:
      - redis-volume:/data
      - ./config/redis.conf:/usr/local/etc/redis/redis.conf:ro
    command: redis-server /usr/local/etc/redis/redis.conf
  
  worker:
    container_name: repository-scraping-worker
    hostname: worker
    image: repository-scraping-worker
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - REDIS_CONNECTION=${REDIS_CONNECTION}
      - MASTER_URL=${MASTER_URL}
      - REPOSITORIES_PATH=${REPOSITORIES_PATH}
    networks:
      - repository-scraper
    depends_on:
      - redis

networks:
  repository-scraper:
    name: repository-scraper

volumes:
  redis-volume:
    name: repository-scraping-redis-volume